name: build_private_grazer_algos_image
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: tags for the image artifact
      dockerfile:
        type: choice
        required: false
        description: the target Dockerfile to build
        options:
          - Dockerfile
          - Dockerfile.remote
jobs:
  build_and_deploy_aip:
    name: build_grazer
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.6"

      - name: setup_qemu
        uses: docker/setup-qemu-action@v2

      - name: setup_buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.ECR_ASSUME_ROLE }}
          role-external-id: grazebuilder
          role-duration-seconds: 1200
          role-session-name: grazebuild
          role-skip-session-tagging: true
          aws-region: ${{ secrets.CONTAINER_REGION }}

      - name: login_to_ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "false"

      - name: build_and_push.remote
        uses: docker/build-push-action@v4
        with:
          file: ${{inputs.dockerfile}}
          context: .
          push: true
          tags: |
            ${{secrets.CONTAINER_REPO}}:${{ inputs.tag }}
          builder: ${{ steps.setup_buildx.name }}
          platforms: linux/amd64

      - name: discord_notify_hook
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DEV_CHANNEL_DISCORD_WEBHOOK }}
          title: "Grazer ${{ inputs.tag }} Built and Pushed"
          message: "**Download: ${{secrets.CONTAINER_REPO}}:${{inputs.tag}}**"
          include_image: true
          custom_image_url: https://avatars.githubusercontent.com/u/196731666?s=400&v=4
          avatar_url: https://avatars.githubusercontent.com/u/196731666?s=48&v=4
          username: Graze Deploy Bot
          colour: "#0090ff"
